import type {
  Card,
  Notification,
  Profile,
  Rewards,
  SavingsGoal,
  Transaction,
  Wallet,
} from '@/types';

const DEMO_USER_ID = 'demo-user-001';

export const mockProfile: Profile = {
  id: DEMO_USER_ID,
  full_name: 'Aisha Rahman',
  phone: '+60123456789',
  avatar_url: null,
  kyc_status: 'verified',
  created_at: '2025-01-15T08:00:00Z',
  updated_at: '2025-05-01T10:00:00Z',
};

export const mockWallets: Wallet[] = [
  {
    id: 'wallet-primary',
    user_id: DEMO_USER_ID,
    name: 'Main Wallet',
    currency: 'MYR',
    balance: 12450.75,
    is_primary: true,
    status: 'active',
    created_at: '2025-01-15T08:00:00Z',
    updated_at: '2025-05-15T12:00:00Z',
  },
  {
    id: 'wallet-savings',
    user_id: DEMO_USER_ID,
    name: 'Savings',
    currency: 'MYR',
    balance: 5200.0,
    is_primary: false,
    status: 'active',
    created_at: '2025-02-01T08:00:00Z',
    updated_at: '2025-05-10T09:00:00Z',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-1',
    wallet_id: 'wallet-primary',
    type: 'payment',
    amount: 45.9,
    balance_after: 12450.75,
    description: 'GrabFood',
    category: 'food',
    merchant_name: 'Grab',
    reference_id: 'TXN-ABC123',
    status: 'completed',
    metadata: {},
    created_at: '2025-05-15T14:30:00Z',
  },
  {
    id: 'tx-2',
    wallet_id: 'wallet-primary',
    type: 'transfer_in',
    amount: 500,
    balance_after: 12496.65,
    description: 'From Ahmad',
    category: 'transfer',
    merchant_name: null,
    reference_id: 'TXN-DEF456',
    status: 'completed',
    metadata: {},
    created_at: '2025-05-14T09:15:00Z',
  },
  {
    id: 'tx-3',
    wallet_id: 'wallet-primary',
    type: 'topup',
    amount: 200,
    balance_after: 11996.65,
    description: 'FPX Top Up',
    category: 'topup',
    merchant_name: 'Maybank',
    reference_id: 'TOP-GHI789',
    status: 'completed',
    metadata: {},
    created_at: '2025-05-13T18:00:00Z',
  },
  {
    id: 'tx-4',
    wallet_id: 'wallet-primary',
    type: 'transfer_out',
    amount: 150,
    balance_after: 11796.65,
    description: 'Rent split',
    category: 'transfer',
    merchant_name: null,
    reference_id: 'TXN-JKL012',
    status: 'completed',
    metadata: {},
    created_at: '2025-05-12T11:20:00Z',
  },
  {
    id: 'tx-5',
    wallet_id: 'wallet-primary',
    type: 'payment',
    amount: 89.0,
    balance_after: 11946.65,
    description: 'Shopee',
    category: 'shopping',
    merchant_name: 'Shopee',
    reference_id: 'TXN-MNO345',
    status: 'completed',
    metadata: {},
    created_at: '2025-05-11T16:45:00Z',
  },
  {
    id: 'tx-6',
    wallet_id: 'wallet-primary',
    type: 'reward',
    amount: 25,
    balance_after: 12035.65,
    description: 'Cashback reward',
    category: 'rewards',
    merchant_name: 'Athris',
    reference_id: 'RWD-PQR678',
    status: 'completed',
    metadata: {},
    created_at: '2025-05-10T08:00:00Z',
  },
];

export const mockCards: Card[] = [
  {
    id: 'card-1',
    wallet_id: 'wallet-primary',
    card_number_last4: '4829',
    card_type: 'virtual',
    status: 'active',
    spending_limit: 5000,
    online_payments: true,
    expires_at: '2028-12-31',
    created_at: '2025-02-01T08:00:00Z',
  },
];

export const mockRewards: Rewards = {
  id: 'rewards-1',
  user_id: DEMO_USER_ID,
  points_balance: 2840,
  tier: 'gold',
  total_points_earned: 5200,
  created_at: '2025-01-15T08:00:00Z',
  updated_at: '2025-05-15T12:00:00Z',
};

export const mockSavingsGoals: SavingsGoal[] = [
  {
    id: 'goal-1',
    user_id: DEMO_USER_ID,
    name: 'Emergency Fund',
    target_amount: 10000,
    current_amount: 6500,
    target_date: '2025-12-31',
    icon: 'shield',
    status: 'active',
    created_at: '2025-02-01T08:00:00Z',
    updated_at: '2025-05-01T10:00:00Z',
  },
  {
    id: 'goal-2',
    user_id: DEMO_USER_ID,
    name: 'Bali Trip',
    target_amount: 5000,
    current_amount: 2100,
    target_date: '2025-08-15',
    icon: 'airplane',
    status: 'active',
    created_at: '2025-03-01T08:00:00Z',
    updated_at: '2025-05-01T10:00:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    user_id: DEMO_USER_ID,
    type: 'transaction',
    title: 'Payment successful',
    message: 'RM 45.90 paid to GrabFood',
    read: false,
    metadata: { transactionId: 'tx-1' },
    created_at: '2025-05-15T14:30:00Z',
  },
  {
    id: 'notif-2',
    user_id: DEMO_USER_ID,
    type: 'security',
    title: 'New login detected',
    message: 'Sign-in from iPhone 15 Pro in Kuala Lumpur',
    read: false,
    metadata: {},
    created_at: '2025-05-15T08:00:00Z',
  },
  {
    id: 'notif-3',
    user_id: DEMO_USER_ID,
    type: 'npc',
    title: 'Nova insight',
    message: 'You spent 23% more on food this week. Want tips to save?',
    read: true,
    metadata: {},
    created_at: '2025-05-14T20:00:00Z',
  },
  {
    id: 'notif-4',
    user_id: DEMO_USER_ID,
    type: 'reward',
    title: 'Cashback earned',
    message: 'You earned RM 25 cashback on your Shopee purchase',
    read: true,
    metadata: {},
    created_at: '2025-05-10T08:00:00Z',
  },
];

export const spendingByCategory = [
  { category: 'Food', amount: 420, percentage: 32 },
  { category: 'Shopping', amount: 310, percentage: 24 },
  { category: 'Transport', amount: 180, percentage: 14 },
  { category: 'Bills', amount: 250, percentage: 19 },
  { category: 'Other', amount: 140, percentage: 11 },
];

export const DEMO_USER = {
  id: DEMO_USER_ID,
  email: 'aisha@demo.athris.app',
  fullName: 'Aisha Rahman',
};
